Import-Module .\Testimo.psd1 -Force #-Verbose

# this will get you available sources
Get-TestimoSources

<# Currently something like this. You can use this list to ExcludeSources or define Sources for Invoke-Testimo
DCDFSRAutoRecovery
DCDiskSpace
DCDnsNameServes
DCDnsResolveExternal
DCDnsResolveInternal
DCLDAP
DCOperatingSystem
DCPingable
DCPorts
DCRDPPorts
DCRDPSecurity
DCServices
DCSMBProtocols
DCSMBShares
DCTimeSettings
DCTimeSynchronizationExternal
DCTimeSynchronizationInternal
DCWindowsFirewall
DCWindowsRemoteManagement
DCWindowsRolesAndFeatures
DCWindowsUpdates
DomainDNSForwaders
DomainDNSScavengingForPrimaryDNSServer
DomainDnsZonesAging
DomainEmptyOrganizationalUnits
DomainGroupPolicyMissingPermissions
DomainKerberosAccountAge
DomainOrphanedForeignSecurityPrincipals
DomainPasswordComplexity
DomainRoles
DomainSecurityGroupsAccountOperators
DomainSecurityGroupsSchemaAdmins
DomainSecurityUsersAcccountAdministrator
DomainSysVolDFSR
DomainTrusts
DomainWellKnownFolders
ForestBackup
ForestOptionalFeatures
ForestOrphanedAdmins
ForestReplication
ForestRoles
ForestSiteLinks
ForestSiteLinksConnections
ForestSites
ForestTombstoneLifetime
#>